version: "2"
services:
#  mssql:
  #    image: mcr.microsoft.com/mssql/server:2017-CU19-ubuntu-16.04
  #    ports:
  #      - "1433:1433"
  #    environment:
  #      SA_PASSWORD: "Password0!"
  #      ACCEPT_EULA: "Y"
  #    volumes:
  #      - ./docker_volume/BACKUP/KEEP:/var/opt/mssql/backups
  #      - ./docker_volume/datafiles:/var/opt/sqlserver
  #      - ./docker_volume/system:/var/opt/mssql
  web:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - "./backend:/usr/src/app"
